# Lab Assignment 1: Rock, Paper, Scissors

## Write and Run Your Own Code to Implement a Rock-Paper-Scissors Model

In [ ]:
# Library Declarations
import numpy as np
import random

np.random.seed(0)
random.seed(0)


In [19]:
# Data extraction here: extract the data from the txt file to python input
# One suggestion is using integers 0,1,2 for rock paper scissor
# and using CPU guess, your guess and score (1 if you win; -1 if you lose; 0 for draw) as possible data
demo_data = np.loadtxt(r"./demo_data.txt", dtype=int) .reshape(-1,3)
print("The data in this file has been stored in a NumPy array of size {}.".format(demo_data.shape))
print(demo_data)

The data in this file has been stored in a NumPy array of size (5, 3).
[[ 0  1  1]
 [ 0  2 -1]
 [ 1  0 -1]
 [ 2  0  1]
 [ 0  0  0]]


In [20]:
np.random.seed(0)
random.seed(0)

history = np.loadtxt(r"./training.txt", dtype=int).reshape(-1,3)
#Define your algorithm here or define your own functions and procedure
def rock_paper_scissor(history=None, last_choice=None):
    # define your function here
    return random.randint(0,2)


C:\Users\werer\AppData\Local\Temp\ipykernel_7488\135062288.py:4: UserWarning: loadtxt: input contained no data: "./training.txt"
  history = np.loadtxt(r"./training.txt", dtype=int).reshape(-1,3)


In [21]:
print(f'Algorithm says you should choose: {rock_paper_scissor(history)}')

Algorithm says you should choose: 1


## What to Submit?
1. A link to your repository (remember to add your Lab TA as a collaborator to this repository, or they won't be able to grade your work!).
2. Your training data in training.txt.
3. Your model evaluation data.
4. A brief write-up describing your algorithm in a couple of sentences, including figures if necessary (your design on paper).
5. Finally, please individually briefly reflect on your experience in a couple of sentences. What are you taking away from this lab? 